/* Bundles the Speak Tool pack-list extension into ONE droppable file.
 *
 * There is one source of truth for the packing rules — speak_tool_html/engine.js —
 * and this build copies it rather than forking it. Six divergent copies of a
 * station script is exactly the failure this project already paid for.
 *
 *   node packlist_extension/build.js
 */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');

const parts = [
  ['reference data (names master + Lampshade SOT)', 'speak_tool_html/reference-data.js'],
  ['packing rules engine',                          'speak_tool_html/engine.js'],
  ['pack list extension (UI, speech, voice)',       'packlist_extension/src/speak-extension.js'],
];

const stamp = process.env.BUILD_DATE || '';
let out = `/* Speak Tool — Order Pack List extension  (single-file build${stamp ? ', ' + stamp : ''})
 *
 * Add ONE line before </body> of the pack list page:
 *     <script src="packlist-speak.js"></script>
 *
 * It adds a fixed control bar and a collection dialog. It does not change,
 * remove or restyle any existing element on the page.
 *
 * Built from:
${parts.map(([label, f]) => ` *   ${f}   — ${label}`).join('\n')}
 * Do not edit this file. Edit the sources above and re-run:
 *     node packlist_extension/build.js
 */
`;

for (const [label, f] of parts) {
  const src = fs.readFileSync(path.join(root, f), 'utf8');
  out += `\n/* ===== ${f} — ${label} ===== */\n${src}\n`;
}

const dest = path.join(__dirname, 'packlist-speak.js');
fs.writeFileSync(dest, out);
console.log(`built ${path.relative(root, dest)}  ${(out.length / 1024).toFixed(0)} KB  from ${parts.length} sources`);

/* ---------------------------------------------------------------------------
 * speak-loader.html — the upload page, with the bundle carried inside it so the
 * loader is one self-contained file that works from a USB stick or file://.
 *
 * The only escaping needed is "</script", which would otherwise close the
 * <script type="text/plain"> block early. The loader reverses it before use.
 * ------------------------------------------------------------------------- */
const tpl = fs.readFileSync(path.join(__dirname, 'src', 'speak-loader.template.html'), 'utf8');
if (tpl.indexOf('/*__BUNDLE__*/') === -1) {
  console.error('speak-loader.template.html has no /*__BUNDLE__*/ placeholder — nothing to fill.');
  process.exit(1);
}
/* Base64, not escaped text.
 *
 * The payload used to be the raw JavaScript with "</script" and "<!--" escaped.
 * That worked, but it left 144 tag-looking sequences inside the block - "<li",
 * "<script", even "i < nodes.length" - and every HTML validator that reads the
 * file reports the closing tags as unbalanced. Base64 contains only
 * [A-Za-z0-9+/=], so there is nothing left for a parser or a linter to misread,
 * and no escaping rules to remember. */
const inert = Buffer.from(out, 'utf8').toString('base64');
const loader = tpl.replace('/*__BUNDLE__*/', () => inert);
const lDest = path.join(__dirname, 'speak-loader.html');
fs.writeFileSync(lDest, loader);
console.log(`built ${path.relative(root, lDest)}  ${(loader.length / 1024).toFixed(0)} KB  (bundle embedded)`);

/* Speak-Tool.html — the same file under the name to hand to someone else.
 * Written by the build rather than copied by hand, because a second copy that
 * can go stale is exactly how the wrong file gets sent. */
const sendDest = path.join(root, 'Speak-Tool.html');
fs.writeFileSync(sendDest, loader);
console.log(`built ${path.relative(root, sendDest)}  — the single file to send`);
