-- ===========================================================================
-- daily_task.tbl_stfc_sarujanan — backfill for 2026-08-17 (REQ-03-D01)
-- ===========================================================================
-- Safe to re-run. The table is created only if absent, and the INSERT relies on
-- the existing UNIQUE (daily_requirement_submitted_date, requirement_id,
-- deliverable_id) constraint to update in place rather than duplicate.
--
-- Days covered by daily_logs/ : 2026-08-13, 2026-08-14, 2026-08-17
-- Already in the CSV export   : 2026-08-13, 2026-08-14
-- Missing                     : 2026-08-17   <-- this file
-- 2026-08-15 and 2026-08-16 were a Saturday and Sunday; no work days are absent.
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS daily_task;

CREATE TABLE IF NOT EXISTS daily_task.tbl_stfc_sarujanan (
    id                                SERIAL PRIMARY KEY,
    daily_requirement_submitted_date  DATE        NOT NULL,
    expected_deadline_date            DATE,
    end_user                          TEXT,
    expected_roi                      TEXT,
    developer                         TEXT        NOT NULL,
    task_assigned_by                  TEXT,
    project                           TEXT,
    project_code                      TEXT        NOT NULL,
    phase                             TEXT,
    requirement_id                    TEXT        NOT NULL,
    deliverable_id                    TEXT        NOT NULL,
    blos_keys                         TEXT,
    domain                            TEXT,
    task_name                         TEXT,
    business_purpose                  TEXT,
    source_system                     TEXT,
    source_tables                     TEXT,
    filter_conditions                 TEXT,
    planned_benefits                  TEXT,
    work_summary                      TEXT,
    gaps_found                        TEXT,
    decisions_made                    TEXT,
    failure_modes                     TEXT,
    company_knowledge                 TEXT,
    code_changed                      BOOLEAN     DEFAULT FALSE,
    files_changed                     INTEGER     DEFAULT 0,
    tests_passed                      INTEGER     DEFAULT 0,
    status                            TEXT,
    benefit_status                    TEXT,
    three_am_standard                 BOOLEAN     DEFAULT TRUE,
    llm_queryable                     BOOLEAN     DEFAULT TRUE,
    company_knowledge_candidate       BOOLEAN     DEFAULT TRUE,
    evidence_location                 TEXT,
    created_at                        TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_stfc_sarujanan_day_deliverable
        UNIQUE (daily_requirement_submitted_date, requirement_id, deliverable_id)
);

INSERT INTO daily_task.tbl_stfc_sarujanan (
    daily_requirement_submitted_date, expected_deadline_date, end_user, expected_roi,
    developer, task_assigned_by, project, project_code, phase,
    requirement_id, deliverable_id, blos_keys, domain,
    task_name, business_purpose, source_system, source_tables, filter_conditions,
    planned_benefits, work_summary, gaps_found, decisions_made, failure_modes,
    company_knowledge, code_changed, files_changed, tests_passed,
    status, benefit_status, three_am_standard, llm_queryable,
    company_knowledge_candidate, evidence_location
) VALUES (
 '2026-08-17',
 '2026-08-24',
 'Postage & Warehouse Team',
 'Stop silent and mis-ordered picking at Unit 3 Lampshade. 46 of 156 rows produced no speech at all while their picture was on screen, and 16 lampshades never entered a collection; each one is a mis-pick or a missed item the packer cannot detect',
 'Sarujanan',
 'Varmen',
 'Speech Tool — Warehouse Voice Packing',
 'STFC',
 'Development — phase 03',
 'REQ-03',
 'REQ-03-D01',
 'lampshade_prefix_rule = LS; packing_priority_conditional (rect present: RectRose=1, Shade=2, Bulb=3, Other=4 | rect absent: Shade=1, Rose=2, Bulb=3, Other=4); lampshade_collection_max = 15; colour_authority = Lampshade SOT; speak_dialog_width_px = 1600; collection_card_width_px = 232',
 'Warehouse Operations — Order Packing',
 'Speech Tool — SKU Integrity Repair, SOT Classification Authority, and Component-Wise Packing Flow',
 'The packer was being shown product images with no spoken instruction, was hearing components in the wrong order, and was seeing two customers'' items merged into a single parcel view. Each produces a wrong parcel that nobody downstream can detect.',
 'Google Sheets + Google Apps Script — Unit 3 Lampshade station',
 '1AMQMzxu (Sheet1, Cleaned Data); 16rx5Dz (names master); 1b9n4Rhy (Lampshade SOT, gid 1477049419)',
 'Station: Unit 3 Lampshade only; data scope Sheet1 to Cleaned Data pipeline; speech scope the client JavaScript generated by speakTextDialog(); excluded: the other 5 stations, the shared names master, the Lampshade SOT source data',
 'No order line silent while its picture is displayed; every LS-prefixed product treated as a lampshade and entering the collection; a combo read one component per Next so each item can be boxed before the next is heard; one customer order never shown as two entries and two customers never sharing one entry; colour sourced from the Lampshade SOT instead of a partial 29-code lookup',
 'Disabled blankDuplicateSKUsInSheet1() in sku.gs, which had blanked duplicate SKUs across Sheet1 (60 rows) and was called by nothing, so it had been run by hand; moved the packing-priority sort to run AFTER addCombinedSKUSet() via a new ppSortCleanedSheetRows(), correcting a regression I introduced on 2026-08-14 that split single customer orders into two; ended combo component sets at a customer boundary in addCombinedSKUSet(); added the customer to the queue group key in Lithursan.gs while keeping the displayed label unchanged; replaced the shade-keyword test with a pure LS prefix rule in ppProductType(); wired the Lampshade SOT as the colour and image authority via ppLoadSot() with a 6-SKU override where the SOT contradicts its own product name; rebuilt the collection view as image cards with a quantity badge and widened the dialog to 1600px; changed speech to one component per Next with postcode and note riding on the last component; announced nameless SKUs as "This one" plus colour instead of skipping them; took thumbnails from each row rather than a per-SKU map so duplicate SKUs keep both images',
 '48 of 169 Sheet1 rows still carry no SKU (36 recoverable, 12 never supplied by the platform); 14 SKUs across 19 rows are absent from the names master and speak as "This one"; 16 of 156 rows were mis-filed as OTHER despite an LS prefix, so they were both mis-ordered and absent from the collection; 111 of 452 lampshade SKUs had no colour from the suffix table; 6 SOT SKUs carry an Outer_Colour that contradicts their own Product_Name; one combo set crossed a customer boundary and put two customers in one parcel view; the names master also holds placeholder text across 210 SKUs (This one Black 125, blank 123, This one 73)',
 'LS prefix alone identifies a lampshade (451/451 against the SOT where the keyword rule missed 9); the priority sort must run last because addCombinedSKUSet() depends on original row order; combo sets end at a customer boundary; the queue group key includes the customer because the SKU string identifies a product set not an order; the SOT is the colour authority with the suffix table as fallback; the SOT product name beats its colour cell where they contradict; postcode and note ride on the last component so no extra Next is needed; quantity is blanked only when there is neither name nor SKU; the names master will not be corrected by us; no SKU recovery script will run without approval',
 'A row with a SKU but no name is announced as "This one" plus colour; a row with neither SKU nor name is still silent (open decision, 12 rows including a 10-bulb order); an unreachable SOT is logged and falls back to the suffix table without breaking the run; the SOT tab is located by finding SKU_ID in header row 2 so a changed gid still works; a missing Colour column is looked up optionally and does not abort; the same SKU twice in one order with different images now yields both thumbnails; a combo component with no row of its own still gets a thumbnail from the second pass; an order with no component rows still speaks its postcode; numeric pack suffixes are deliberately not stripped for size because they are genuinely ambiguous',
 'A silent row is more dangerous than a wrong row: the display path (Image URLs) and the speech path (SKU to name) have different inputs, so when the speech path broke the packer still saw a picture and heard nothing, with no error to report. Derived columns must not be treated as source data; Combo SKU arrives from the platform and is then overwritten, and two separate defects were both that rewrite. Order-dependent transforms must declare their dependency, because adding a sort upstream corrupted addCombinedSKUSet() with no error. Free-text names maintained by another team are not a classification key; a SKU prefix is a structural fact while a spoken name is editorial content. Verify a recovery before offering it: positional SKU reconstruction looked plausible at 73%, reached 97% once pack suffixes were ignored, and was confirmed on 92% of the target rows by cross-checking an independent Combo Color column.',
 TRUE,
 4,
 9,
 'In Progress',
 'Partial — all defects fixed and verified against live data; Sheet1 re-import and two rule decisions outstanding',
 TRUE,
 TRUE,
 TRUE,
 '/validation/issues/unit-3-sku-blanking.md; /validation/missing-names-checklist.md; /capability/unit3-packing-priority-report.md; /scripts/Unit 3 Lampshade/'
)
ON CONFLICT (daily_requirement_submitted_date, requirement_id, deliverable_id)
DO UPDATE SET
    work_summary      = EXCLUDED.work_summary,
    gaps_found        = EXCLUDED.gaps_found,
    decisions_made    = EXCLUDED.decisions_made,
    failure_modes     = EXCLUDED.failure_modes,
    company_knowledge = EXCLUDED.company_knowledge,
    status            = EXCLUDED.status,
    benefit_status    = EXCLUDED.benefit_status,
    files_changed     = EXCLUDED.files_changed,
    tests_passed      = EXCLUDED.tests_passed,
    evidence_location = EXCLUDED.evidence_location;

-- Verification
SELECT id, daily_requirement_submitted_date, developer, project_code, phase,
       requirement_id, deliverable_id, status, benefit_status,
       code_changed, files_changed, tests_passed, created_at
FROM   daily_task.tbl_stfc_sarujanan
WHERE  project_code = 'STFC' AND developer = 'Sarujanan'
ORDER  BY daily_requirement_submitted_date;

SELECT COUNT(*) AS total_rows FROM daily_task.tbl_stfc_sarujanan;
